# @author: huanjing
# @file: 2023/4/14
# time: 2023-04-14 16:21
import random
import time


def get_huanjing():
    huanjing_dict = {
        "STYLE": 1,
        "SCRIPT": random.randint(1, 7),
        "A": 1,
        "DIV": 3,
        "LABEL": 2,
        "INPUT": 2,
        "textLength": random.randint(3800, 3800),
        "HTMLLength": random.randint(5200, 5300),
        "documentMode": "CSS1Compat",
        "browserLanguage": "zh-CN",
        "browserLanguages": "zh-CN,zh",
        "devicePixelRatio": 1,
        "colorDepth": 24,
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
        "cookieEnabled": 1,
        "netEnabled": 1,
        "innerWidth": random.randint(1000, 1200),
        "innerHeight": random.randint(100, 300),
        "outerWidth": random.randint(1000, 1200),
        "outerHeight": random.randint(1000, 1200),
        "screenWidth": 1920,
        "screenHeight": 1080,
        "screenAvailWidth": 1920,
        "screenAvailHeight": random.randint(1000, 1200),
        "screenLeft": -random.randint(100, 300),
        "screenTop": random.randint(100, 300),
        "screenAvailLeft": -random.randint(100, 300),
        "screenAvailTop": 0,
        "localStorageEnabled": 1,
        "sessionStorageEnabled": 1,
        "indexedDBEnabled": 1,
        "platform": "Win32",
        "doNotTrack": 0,
        "timezone": -8,
        "canvas2DFP": ''.join([random.choice('0123456789abcdef') for _ in range(32)]),
        "canvas3DFP": 0,
        "plugins": "internal-pdf-viewer,internal-pdf-viewer,internal-pdf-viewer,internal-pdf-viewer,internal-pdf-viewer",
        "maxTouchPoints": 20,
        "flashEnabled": -1,
        "javaEnabled": 0,
        "hardwareConcurrency": 8,
        "jsFonts": "Arial,ArialBlack,ArialNarrow,Calibri,Cambria,CambriaMath,ComicSansMS,Consolas,Courier,CourierNew,Georgia,Helvetica,Impact,LucidaConsole,LucidaSansUnicode,MicrosoftSansSerif,MSGothic,MSPGothic,MSSansSerif,MSSerif,PalatinoLinotype,SegoePrint,SegoeScript,SegoeUI,SegoeUILight,SegoeUISemibold,SegoeUISymbol,Tahoma,Times,TimesNewRoman,TrebuchetMS,Verdana,Wingdings",
        "mediaDevices": -1,
        "timestamp": int(time.time()*1000),
        "deviceorientation": -1,
        "touchEvent": -1,
        "performanceTiming": -1,
        "internalip": -1
    }
    huanjing_list = [
    "textLength",
    "HTMLLength",
    "documentMode",
    "A",
    "ARTICLE",
    "ASIDE",
    "AUDIO",
    "BASE",
    "BUTTON",
    "CANVAS",
    "CODE",
    "IFRAME",
    "IMG",
    "INPUT",
    "LABEL",
    "LINK",
    "NAV",
    "OBJECT",
    "OL",
    "PICTURE",
    "PRE",
    "SECTION",
    "SELECT",
    "SOURCE",
    "SPAN",
    "STYLE",
    "TABLE",
    "TEXTAREA",
    "VIDEO",
    "screenLeft",
    "screenTop",
    "screenAvailLeft",
    "screenAvailTop",
    "innerWidth",
    "innerHeight",
    "outerWidth",
    "outerHeight",
    "browserLanguage",
    "browserLanguages",
    "systemLanguage",
    "devicePixelRatio",
    "colorDepth",
    "userAgent",
    "cookieEnabled",
    "netEnabled",
    "screenWidth",
    "screenHeight",
    "screenAvailWidth",
    "screenAvailHeight",
    "localStorageEnabled",
    "sessionStorageEnabled",
    "indexedDBEnabled",
    "CPUClass",
    "platform",
    "doNotTrack",
    "timezone",
    "canvas2DFP",
    "canvas3DFP",
    "plugins",
    "maxTouchPoints",
    "flashEnabled",
    "javaEnabled",
    "hardwareConcurrency",
    "jsFonts",
    "timestamp",
    "performanceTiming",
    "internalip",
    "mediaDevices",
    "DIV",
    "P",
    "UL",
    "LI",
    "SCRIPT",
    "deviceorientation",
    "touchEvent"
]
    dd = []
    for hj in huanjing_list:
        try:
            dd.append(huanjing_dict[hj])
        except:
            dd.append("-1")
    result_text = ""
    for i in dd:
        result_text += str(i) + "!!"
    # return "3835!!5259!!CSS1Compat!!1!!-1!!-1!!-1!!-1!!-1!!-1!!-1!!-1!!-1!!2!!2!!-1!!-1!!-1!!-1!!-1!!-1!!-1!!-1!!-1!!-1!!1!!-1!!-1!!-1!!-1663!!69!!-1920!!0!!1637!!182!!1653!!845!!zh-CN!!zh-CN,zh!!-1!!1!!24!!Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36!!1!!1!!1920!!1080!!1920!!1040!!1!!1!!1!!-1!!Win32!!0!!-8!!2d7a3f4ebbe8b0c8b98a595e5ef5d1fe!!0!!internal-pdf-viewer,internal-pdf-viewer,internal-pdf-viewer,internal-pdf-viewer,internal-pdf-viewer!!20!!-1!!0!!8!!Arial,ArialBlack,ArialNarrow,Calibri,Cambria,CambriaMath,ComicSansMS,Consolas,Courier,CourierNew,Georgia,Helvetica,Impact,LucidaConsole,LucidaSansUnicode,MicrosoftSansSerif,MSGothic,MSPGothic,MSSansSerif,MSSerif,PalatinoLinotype,SegoePrint,SegoeScript,SegoeUI,SegoeUILight,SegoeUISemibold,SegoeUISymbol,Tahoma,Times,TimesNewRoman,TrebuchetMS,Verdana,Wingdings!!1681723055713!!-1!!-1!!-1!!3!!-1!!-1!!-1!!7!!-1!!-1"
    return result_text[:-2]


if __name__ == '__main__':
    print(get_huanjing())
